#!/bin/bash

# Get screen size:
X=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)
Y=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

fontSize=$(expr \( $Y + $X \) / 180 )
Y=$(expr \( $Y \* 20 \) / \( 33 \* $fontSize \))
X=$(expr \( $X \* 20 \) / \( 20 \* $fontSize \))

st -n spfm -g $(echo "$X""x""$Y") -f $(echo "Inconsolata:pixelsize=""$fontSize"":antialias=true:autohint=true:spacing=""0") -e ranger
