#!/bin/bash

while test $# -gt 0; do
	case "$1" in
		-r|--random)
			mode="random"
			shift;;
		-s|--set)
			mode="set"
			shift
			image=$1
			shift;;
		-h|--help)
			echo "Wallpaper setter"
			echo " "
			echo "-r, --random   picks a random wallpaper"
			echo "-s, --set      set wallpaper to image"
			exit 0;;
		*)
			echo "unknown flag use --help for more info"
			exit 1;;
	esac
done

swayPid="$(pidof swaybg)"
if [ $mode == "random" ]; then
    if [ "$XDG_SESSION_TYPE" == "wayland" ]; then
        swaybg -m fill -i ~/Wallpapers/$(ls ~/Wallpapers/ | shuf -n 1) &
        disown
        [ "$swayPID" == "" ] || ( sleep 2s && kill -9 $swayPid ) &
    else
        feh --bg-fill -z ~/Wallpapers/*
        exit 0
    fi
fi

echo $mode $image
if [ $mode == "set" ]; then
    if [$XDG_SESSION_TYPE == "wayland"]; then
        swaybg -m fill -i $image &
        disown
        [ "$swayPID" == "" ] || ( sleep 2s kill -9 $swayPid ) &
    else
        feh --bg-fill $image
        exit 0
    fi
fi

exit 0
